apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 167239449235.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        ports:
        - containerPort: 3306